/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktra;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thang
 */
public class KhachHang extends javax.swing.JInternalFrame {
    ArrayList<KhachHang2> khachhangList;
   
    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        loadListKhachHang();
    }
    
     private Connection conn;
    private PreparedStatement stmt = null;
    private ResultSet rs = null;
    
    public ArrayList<KhachHang2> getKhachhangList() {   
        Cnn data = new Cnn();
        conn = data.getConnection();
        ArrayList<KhachHang2> khachhangList = new ArrayList<KhachHang2>();
        PreparedStatement ps = null;
        String sql_select = "select * from khachhang";
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(sql_select);
            rs = ps.executeQuery();
            while (rs.next()) {
               String makh = rs.getString("makh");
               String tenkh = rs.getString("tenkh");
               int dthoai = rs.getInt("dthoai");
               khachhangList.add(new KhachHang2(makh, tenkh, dthoai));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return khachhangList;
    }
    private void loadListKhachHang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
       khachhangList= getKhachhangList();
        Object rowData[] = new Object[model.getColumnCount()];
        for (int i = 0; i < khachhangList.size(); i++) {
            rowData[0] = khachhangList.get(i).getMakh();
            rowData[1] = khachhangList.get(i).getTenkh();
            rowData[2] = khachhangList.get(i).getDthoai();
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Danh sách");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin khách hàng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Họ và tên", "Số điện thoại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
